name: ptero

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: make ptero directorys
      run: |
        sudo mkdir -p /etc/pterodactyl
        curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"
        sudo chmod u+x /usr/local/bin/wings

    - name: install neofetch
      run: |
        sudo apt install sudo neofetch

    - name: neofetch shit
      run: |
        neofetch

    - name: domain setup
      run: |
        sudo mkdir /etc/letsencrypt
        sudo mkdir /etc/letsencrypt/live
        sudo mkdir /etc/letsencrypt/live/usa1.hyghj.eu.org
        cd /etc/letsencrypt/live/usa1.hyghj.eu.org
        sudo openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj "/C=NA/ST=NA/L=NA/O=NA/CN=Generic SSL Certificate" -keyout privkey.pem -out fullchain.pem

        
    - name: cftunnel this shit
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
        sudo dpkg -i cloudflared.deb && sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiNjU1ODcxYzUtYTc2MC00NTQzLWEzN2ItMzY5NjliYzQ0ZThlIiwicyI6IlltWmlOVGcyTjJVdFpHRXhOUzAwTkRVekxUbGxaREV0T1RCak56UXdObVptWVRSayJ9
        
    - name: config
      run: |
        cd /etc/pterodactyl && sudo wings configure --panel-url https://panel.astralaxis.one --token ptla_ow7tyaIqnPooG1uX2mcVf0aVAkQUdOl1qLzF6wxJE1P --node 14

    - name: start
      run: |
        sudo wings --debug
        
