name: ptero

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: make ptero directorys
      run: |
        sudo mkdir -p /etc/pterodactyl
        curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"
        sudo chmod u+x /usr/local/bin/wings

    - name: install neofetch
      run: |
        apt install sudo neofetch
        neofetch

        
