name: ptero

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Stop existing tmate sessions
      run: |
        pkill -9 tmate || true
        
    - name: Download and extract tmate
      run: |
        wget -nc https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-i386.tar.xz &> /dev/null
        tar --skip-old-files -xvf tmate-2.4.0-static-linux-i386.tar.xz &> /dev/null
        
    - name: Start tmate server
      run: |
        rm -f nohup.out
        bash -c './tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock new-session -d'
        bash -c './tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock wait tmate-ready'
        
    - name: Display tmate SSH URL
      run: |
        ./tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock display -p "#{tmate_ssh}"
